name: Build Package
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Run webpack
        run: yarn lint:fix

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: dist
          message: "ci(build): build source code [${{ github.sha }}]]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}